import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Welcome my e-commerce</h1>
         <nav>
           <ul>
             <li>
                <Link href={"/tienda"}>tienda</Link>
             </li>
              <li>
                 <Link href={"/carrito"}>categoria</Link>
              </li>
           </ul>
         </nav>

        {children}
        </body>
    </html>
  )
}
